### ISSUE TITLE
CMD seems to require a non existent config file.

### ISSUE THREAD

**Issue by rquadling** [bitnami/bitnami-docker-php-fpm#101]
The php-fpm containers based upon this repo seem to want to use `
CMD ["php-fpm","-F","--pid","/opt/bitnami/php/tmp/php-fpm.pid","-c","/opt/bitnami/php/conf/php-fpm.conf"]` as the runner.

But the config file `/opt/bitnami/php/conf/php-fpm.conf` doesn't seem to exist.

Running `docker run bitnami/php-fpm:7.2 ls -al /opt/bitnami/php` shows 
```
total 48
drwxr-xr-x 1 1001 1001 4096 Feb  1 14:15 .
drwxr-xr-x 1 1001 1001 4096 Feb  1 14:15 ..
drwxr-xr-x 2 1001 1001 4096 Feb  1 12:21 bin
drwxr-xr-x 3 1001 1001 4096 Feb  1 12:21 etc
drwxr-xr-x 3 1001 1001 4096 Feb  1 12:21 include
drwxr-xr-x 3 1001 1001 4096 Feb  1 12:21 lib
drwxr-xr-x 2 1001 1001 4096 Feb  1 12:21 licenses
drwxr-xr-x 2 root root 4096 Feb  1 14:15 logs
drwxr-xr-x 3 1001 1001 4096 Feb  1 12:21 php
drwxr-xr-x 2 1001 1001 4096 Feb  1 12:21 sbin
drwxr-xr-x 2 1001 1001 4096 Jan  1  1970 tmp
drwxr-xr-x 4 1001 1001 4096 Feb  1 12:21 var
```

Running `docker run bitnami/php-fpm:7.2 cat /opt/bitnami/php/conf/php-fpm.conf` shows
```
cat: /opt/bitnami/php/conf/php-fpm.conf: No such file or directory
```

This looks like it should be `/opt/bitnami/php/etc/conf/php-fpm.conf`

Running `docker run bitnami/php-fpm:7.2 ls -al /opt/bitnami/php/etc` shows
```
total 256
drwxr-xr-x 3 1001 1001  4096 Feb  1 12:21 .
drwxr-xr-x 1 1001 1001  4096 Feb  1 14:15 ..
-rw-r--r-- 1 1001 1001    64 Feb  1 12:20 common.conf
-rw-r--r-- 1 1001 1001   425 Feb  1 12:20 environment.conf
-rw-r--r-- 1 1001 1001  1229 Feb  1 12:20 pear.conf
-rw-r--r-- 1 1001 1001  4490 Feb  1 12:20 php-fpm.conf
-rw-r--r-- 1 1001 1001  4473 Feb  1 12:20 php-fpm.conf.default
drwxr-xr-x 2 1001 1001  4096 Feb  1 12:21 php-fpm.d
-rw-r--r-- 1 1001 1001 70732 Feb  1 12:20 php.ini
-rw-r--r-- 1 1001 1001 70218 Feb  1 12:20 php.ini-development
-rw-r--r-- 1 1001 1001 70490 Feb  1 12:20 php.ini-production
```

And running `docker run bitnami/php-fpm:7.2 cat /opt/bitnami/php/etc/php-fpm.conf` shows the config, ending with ...
```
; Include one or more files. If glob(3) exists, it is used to include a bunch of
; files from a glob(3) pattern. This directive can be used everywhere in the
; file.
; Relative path can also be used. They will be prefixed by:
;  - the global prefix if it's been set (-p argument)
;  - /opt/bitnami/php otherwise
include=/opt/bitnami/php/etc/php-fpm.d/*.conf
```
Allowing for additional .conf files to be added to `/opt/bitnami/php/etc/php-fpm.d`.

**Comment by rquadling** [comment]
It also looks like bitnami-bot is setting this automatically from some build system, so I don't think this repo can fix this and persist the fix.

**Comment by rquadling** [comment]
Also, from a phpinfo() using the default image with nginx, `Loaded Configuration File | /opt/bitnami/php/etc/php-fpm.conf`

**Comment by tompizmor** [comment]
Thanks for filling this issue with so many details.
We have just released new images of the php-fpm fixing the issue.

You can check the updated CMD [here](https://github.com/bitnami/bitnami-docker-php-fpm/blob/master/7.2/Dockerfile#L20)

**Comment by rquadling** [comment]
I think it is fine to change this repo, but I'm pretty sure that there is a bot that generates the entire file from scratch, so will, essentially, discard this change. Can that be checked too?

**Comment by tompizmor** [comment]
Yes, It has been already updated so it will be fine for all the future releases.

**Comment by rquadling** [comment]
Can you point me to the repo that handles the builds? I want to include the ability to add additional php.ini files. This will make adding extensions significantly easier. Currently, I have to append `extension=module.so` to the the current php.ini file during the build. It is part of the standard build to support the additional directory.

**Comment by tompizmor** [comment]
@rquadling I am afraid that that repo is not publicly available. 

It seems that php needs to be compiled with the `--with-config-file-scan-dir` option. I will create an internal task in order to add this feature to the php-fpm container.

**Comment by rquadling** [comment]
That would be brilliant. That would then allow us to have external ini files per extension and not have to touch the default ini file. Especially since there's no persistence for the php-fpm container.

**Comment by rquadling** [comment]
@tompizmor Any news on `--with-config-file-scan-dir` being enabled for the Bitnami php-fpm images?

**Comment by tompizmor** [comment]
Hi @rquadling, I am afraid that we didn't find the time yet to work on this. I will raise the issue again internally to see if we can re-prioritize this task.

**Comment by rquadling** [comment]
Is there any way this can be outsourced to non Bitnami developers? I'm happy to sign an NDA and CLA. The PHP-FPM container is very very good, but not quite right for our use. Unfortunately, making it fit requires a rebuild of PHP, which sort of defeats the whole point in using your containers.

**Comment by rquadling** [comment]
I've just found http://php.net/manual/en/configuration.file.php#configuration.file.scan.

Adding an `ENV PHP_INI_SCAN_DIR /opt/bitnami/php/lib/php.d` and appropriate mounting via our docker compose file (also tested with the `-v` option for `docker run`) ... and joy!!!

**Comment by tompizmor** [comment]
These are great news! I didn't know it was possible to configure it via an env var!

**Comment by tompizmor** [comment]
@rquadling I just have created this issue https://github.com/bitnami/bitnami-docker-php-fpm/issues/104 regarding adding support to scan a dir for additional .ini files.

Please consider closing this issue if the main issue has been already addressed.

**Comment by rquadling** [comment]
Yep. Initial issue was relating to the php-fpm.conf file, not php.ini files.
