### ISSUE TITLE
Add support to scan a dir for additional .ini files

### ISSUE THREAD

**Issue by tompizmor** [bitnami/bitnami-docker-php-fpm#104]
As requested in this other issue https://github.com/bitnami/bitnami-docker-php-fpm/issues/101#issuecomment-365329376 it would be nice to have PHP compiled with the `--with-config-file-scan-dir` option so it is possible to mount custom .ini files.

**Comment by juan131** [comment]
Hi @tompizmor 

Do we have any internal task for this? Could we please link it?

**Comment by tompizmor** [comment]
The Bitnami php-fpm container now scans for additional .ini files under `/opt/bitnami/php/etc/conf.d` since the image tags `7.2.3-r2`, `7.1.15-r2`, `7.0.28-r2` and `5.6.34-r2`.

**Comment by rquadling** [comment]
Please update the README.md (Both notable changes as well as PHP configuration is now different).

**Comment by tompizmor** [comment]
Just did it: https://github.com/bitnami/bitnami-docker-php-fpm/commit/772be8def50bfa572b3617f411f3073f6f3a36f6

**Comment by rquadling** [comment]
I'd recommend linking to http://php.net/manual/en/configuration.file.php#configuration.file.scan as well as mentioning that multiple files are loaded in alphabetical order. It is common to have 1 file per extension. Also, using a numeric prefix is a great way of getting some sort of order into the loading of the configuration.

10-base-overrides.ini
20-per-extension.ini
90-environment-specific.ini
99-personal-no-matter-what-overrides.ini

**Comment by tompizmor** [comment]
Thanks for the suggestion. I just update the README!

**Comment by rquadling** [comment]
Thank you.

**Comment by rquadling** [comment]
OOI, any news on when/if the proper persistence layer will be available similar to other containers? It is extremely useful to be able to see what the default, embedded configuration is.

**Comment by tompizmor** [comment]
We have no news regarding this topic yet. 
Can you please let me know why do you think adding persistence for config files is important for this container? 
It is because in previous versions you could mount an empty host folder and it got populated with the default config?

**Comment by rquadling** [comment]
For me, there are 2 main issues and a significant benefit to re-implementing the persistence layer.

1. Without the persistence layer, as a consumer of the container, we do not know what the config is without sniffing through phpinfo().
2. Without the persistence layer, we have no awareness of any changes to the config, be it from a new Bitnami build or from the upstream service having changed the default configuration.
3. Standardisation. In short, what's so special about the PHP container that it can NOT provide the same mechanism of configurations as provided by the Bitnami redis, nginx, mysql containers.

By having the persistence layer, configuration can be placed in our local source control, so when we upgrade a container, the config file is amended and changes become visible. This saves a LOT of effort for a busy developer needing to quickly see what's changed and accepting the changes, or introducing an appropriate php.d/00-core-changes.ini to set the new settings accordingly.

The introduction of the additional ini directory is excellent and so I hope, with the persistence layer, the entire default configuration for PHP and PHP-FPM can be exposed to the consumer of these containers and allowing this container to work the same way as the other containers.

As I see it, the php and php-fpm aspects of this container would exist side by side, each in their own subdirectory within the persistence volume, just like those for other services in the stack.

I've never understood or liked why things need to be 'special'. PHP, and PHP-FPM have configs. Just like nginx, redis, mysql, etc. Why even bother treating them as different? By maintaining the consistency across the set of containers, there's no need to any additional patterns to learn.

**Comment by tompizmor** [comment]
@rquadling I understand your point of view.

The difference between php, node, ruby or python and other containers like mysql, nginx or redis is that they are thought to develop minimal production applications. 

As you may already know, Bitnami uses [nami](https://github.com/bitnami/nami) to configure the applications and servers. This tool is also in charge of controlling the persistence of the applications.

However, including this tool in the image increased the size considerably so we re-implement the container without nami and hence without persistence. That is the main reason why this container is different.

**Comment by rquadling** [comment]
Would a nami-lite be an alternative here. Purely concentrating on config files, rather than any additional data persistence?

**Comment by rquadling** [comment]
I see. I guess a `nami-php` tool would be a pointless overhead. And each container that isn't working with nami would need their own variant.

OK. I'm not sure what else can be done at this stage.

**Comment by tompizmor** [comment]
Right now I think the best way to support persistence would be to extend the current image and implement the persistence manually:

I tried with this Dockerfile:

```
FROM bitnami/minideb-runtimes:jessie-php
LABEL maintainer "Bitnami <containers@bitnami.com>"

# Install required system packages and dependencies
RUN install_packages ca-certificates libbz2-1.0 libc6 libcomerr2 libcurl3 libffi6 libfreetype6 libgcc1 libgcrypt20 libgmp10 libgnutls-deb0-28 libgpg-error0 libgssapi-krb5-2 libhogweed2 libicu52 libidn11 libjpeg62-turbo libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 liblzma5 libncurses5 libnettle4 libp11-kit0 libpng12-0 libpq5 libreadline6 librtmp1 libsasl2-2 libssh2-1 libssl1.0.0 libstdc++6 libsybdb5 libtasn1-6 libtidy-0.99-0 libtinfo5 libxml2 libxslt1.1 wget zlib1g
RUN wget -nc -P /tmp/bitnami/pkg/cache/ https://downloads.bitnami.com/files/stacksmith/php-7.2.4-0-linux-x64-debian-8.tar.gz && \
    echo "5f87d54dbc39f4f0dd30352e14e893949a8e04e3e27e2ca201baf871a825b024  /tmp/bitnami/pkg/cache/php-7.2.4-0-linux-x64-debian-8.tar.gz" | sha256sum -c - && \
    tar -zxf /tmp/bitnami/pkg/cache/php-7.2.4-0-linux-x64-debian-8.tar.gz -P --transform 's|^[^/]*/files|/opt/bitnami|' --wildcards '*/files' && \
    rm -rf /tmp/bitnami/pkg/cache/php-7.2.4-0-linux-x64-debian-8.tar.gz
RUN mkdir -p /bitnami && ln -sf /bitnami/php /bitnami/php-fpm
RUN mkdir /opt/bitnami/php/logs && touch /opt/bitnami/php/logs/php-fpm.log

ENV BITNAMI_APP_NAME="php-fpm" \
    BITNAMI_IMAGE_VERSION="7.2.4-r1" \
    PATH="/opt/bitnami/php/bin:/opt/bitnami/php/sbin:$PATH"

EXPOSE 9000

WORKDIR /app

COPY app-entrypoint.sh /

ENTRYPOINT ["/app-entrypoint.sh"]
CMD ["php-fpm","-F","--pid","/opt/bitnami/php/tmp/php-fpm.pid","-y","/opt/bitnami/php/etc/php-fpm.conf"]
```

And this app-entrypoint.sh

```
#!/bin/bash -e

PERSIST_DIR=/bitnami/php
DATA_TO_PERSIST=/opt/bitnami/php/etc

if [ ! -f ${PERSIST_DIR}/.initialized ]; then
    echo There is no data. Starting from scratch...
    mkdir -p ${PERSIST_DIR}
    cp -r ${DATA_TO_PERSIST} ${PERSIST_DIR}
    rm -rf ${DATA_TO_PERSIST}
    ln -s ${PERSIST_DIR}/etc ${DATA_TO_PERSIST}
    touch ${PERSIST_DIR}/.initialized
else
    echo Data already initialized. Restoring conf files...
    rm -rf ${DATA_TO_PERSIST}
    ln -s ${PERSIST_DIR}/etc ${DATA_TO_PERSIST}
fi

exec "$@"
```

**Comment by rquadling** [comment]
That looks really useful. In other containers, there's a `.restored` file. Can you give some info on its use?

**Comment by tompizmor** [comment]
It is just a flag to know that the folder has been restored from the persistent volume. 

```
#!/bin/bash -e

PERSIST_DIR=/bitnami/php
DATA_TO_PERSIST=/opt/bitnami/php/etc

if [ ! -f ${PERSIST_DIR}/.initialized ]; then
    echo There is no data. Starting from scratch...
    mkdir -p ${PERSIST_DIR}
    cp -r ${DATA_TO_PERSIST} ${PERSIST_DIR}
    rm -rf ${DATA_TO_PERSIST}
    ln -s ${PERSIST_DIR}/etc ${DATA_TO_PERSIST}
    touch ${PERSIST_DIR}/.initialized
else
    echo Data already initialized. Restoring conf files...
    rm -rf ${DATA_TO_PERSIST}
    ln -s ${PERSIST_DIR}/etc ${DATA_TO_PERSIST}
    touch ${DATA_TO_PERSIST}/.restored # Just adding this line is enough to have the same behaviour
fi

exec "$@"
```
