### ISSUE TITLE
Environment variables not loaded

### ISSUE THREAD

**Issue by tuananh** [bitnami/bitnami-docker-php-fpm#106]
So i can see the environment variable in the container (echo works) but it's not listed in `<?php var_export($_SERVER)?>` or `phpinfo`.

**Comment by juan131** [comment]
Hi @tuananh 

Could you please provide more information?

 * Are you using this container with NGINX or Apache? 
 * Did you follow this guide? https://github.com/bitnami/bitnami-docker-php-fpm#connecting-to-other-containers

**Comment by tuananh** [comment]
Im using it with nginx, follow the kubernetes example in example folder.

**Comment by rquadling** [comment]
What is the value of `variables_order`? Also, have you configured CLI and/or PHP-FPM with separate configs?

http://php.net/manual/en/ini.core.php#ini.variables-order

**Comment by tuananh** [comment]
So with this setup https://github.com/bitnami/bitnami-docker-php-fpm/blob/master/example/kubernetes.yml (default config) it won't be able to load environment variables?

This behavior is a bit different with [php](https://hub.docker.com/_/php/) fpm variant

**Comment by rquadling** [comment]
Check the containers 'variables_order' setting to confirm the issue. If it is a problem, add an ini file setting the variables_order appropriate to your requirements. The Bitnami php-fpm containers now support scanning of an additional directory, so injecting additional config is extremely simple.

**Comment by tuananh** [comment]
looks like it's empty. i'm going to use an additional ini file. Thanks for help.

**Comment by rquadling** [comment]
It shouldn't be empty. It should be `GPCS` at least. Adding `E` is fine. Just don't turn on `register_globals`.

**Comment by tuananh** [comment]
Lemme double check them again tmr
