### ISSUE TITLE
New releases have no changelog info.

### ISSUE THREAD

**Issue by rquadling** [bitnami/bitnami-docker-php-fpm#107]
When Bitnami release a new version of the container (by that I mean r1 onwards), there's no documentation regarding why there has been a change. It would be very useful to know why there is a new release as it suggests a change in the container that is not related to the version of PHP that is in the container.

**Comment by carrodher** [comment]
Thanks for reporting it. We agree, for that reason, we have included a task in our backlog to implement this improvement.

**Comment by rquadling** [comment]
We're seeing multiple releases of the containers. Please can we have SOME notes regarding the changes please?

**Comment by carrodher** [comment]
The reason why you can see a large number of releases in the last few days is that we have now started to do daily releases of our containers.
These daily releases only include system packages updates. When an important change in php appears we include this information in the [relases page](https://github.com/bitnami/bitnami-docker-php-fpm/releases) or in the [notable changes](https://github.com/bitnami/bitnami-docker-php-fpm/releases) section in the readme.

Apart from that, we're working to improve the visibility of these changes.
