### ISSUE TITLE
Error getting repository data for rhel-7-server-htb-rpms, repository not found

### ISSUE THREAD

**Issue by YumeMichi** [bitnami/bitnami-docker-php-fpm#114]
I got this error while running docker build in `5.6/rhel-7` directory.

**Comment by carrodher** [comment]
In what operating system are you running `docker build`? As it is a Red Hat image you need to run it in an RHEL OS because the `yum` command used to install packages needs to be registered as a Red Hat product

**Comment by YumeMichi** [comment]
thx
