### ISSUE TITLE
Unable to install PHP extension【ioncube】 

### ISSUE THREAD

**Issue by crcjwice123** [bitnami/bitnami-docker-php-fpm#117]
**Description**

![bug](https://user-images.githubusercontent.com/5734188/50825812-f0e22f80-1374-11e9-8590-15782e7ed5a0.png)

**Steps to reproduce the issue:**

I have followed the instructions by

1. add ioncube_loader_lin_7.1.so in debian-9 dockerfile
`ADD ioncube_loader_lin_7.1.so /opt/bitnami/php/lib/php/extensions/`
2. mount 00-ioncube.ini into /opt/bitnami/php/etc/conf.d
`      - /srv/crm_pro/00-ioncube.ini:/opt/bitnami/php/etc/conf.d/00-ioncube.ini`
3. docker-compose restart

I also tried mount custom php.ini file according to this thread
https://community.bitnami.com/t/php-extension-ioncube-installation-issue/30432

**Describe the results you received:**

But always get following php-fpm error
`[08-Jan-2019 10:36:11] NOTICE: PHP message: PHP Fatal error:  [ionCube Loader] The Loader must appear as the first entry in the php.ini file in Unknown on line 0
`

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Version**

- Output of `docker version`:

```
(paste your output here)
```

- Output of `docker info`:

```
(paste your output here)
```

- Output of `docker-compose version` (if applicable):

```
(paste your output here)
```

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment]
Hi @crcjwice123, thanks for submitting this issue. We are going to look into it.

**Comment by rquadling** [comment]
You could try adding the appropriate priority comment to the top of the 00-ioncube.ini file.

`;priority = 0`

Not sure if it will help.

**Comment by andresbono** [comment]
Thanks @rquadling! Can you try it and let us know if it works, @crcjwice123?
