### ISSUE TITLE
Critical: Image listening on port 9000 now on localhost only

### ISSUE THREAD

**Issue by Kovah** [bitnami/bitnami-docker-php-fpm#119]
**Description**

Starting yesterday, builds with the php-fpm:7.2 images are failing. Upon investigation I found that PHP-FPM is now listening on localhost for port 9000 only, so other services are not able to connect to port 9000 from the outside anymore, e.g. nginx.

**Steps to reproduce the issue:**

1. Setup a container stack with nginx and php-fpm images from Bitnami and follow the setup guides.
2. Add some PHP-based application.
3. Tell nginx to connect to php:9000 for PHP files.
4. All requests will result in a 502 error.

**Error Messages**

nginx provides the following error message:

```
[error] 31#0: *3 connect() failed (111: Connection refused) while connecting to upstream, 
client: 172.19.0.1, server: _, request: "GET / HTTP/1.1", 
upstream: "fastcgi://172.19.0.3:9000", host: "example.com"
```

**Cause of the issue**

**The affected image tag is `7.2.14-debian-9-r20`**. The PHP source package was changed from `php-7.2.14-0-linux-amd64-debian-9` to `php-7.2.14-1-linux-amd64-debian-9` in commit [5dd43d0](https://github.com/bitnami/bitnami-docker-php-fpm/commit/5dd43d018520c732ab34f7666ed9a8f9fc9afbc9#diff-ea1d8c1f263497063e92afec077e0a7e)

I couldn't find the exact change in these packages which result in the ultimate change that broke the container, but there was one critical change made in the file **`/opt/bitnami/php/etc/php-fpm.d/www.conf`** line 36:

```
listen = 9000
```
was changed to 
```
listen = 127.0.0.1:9000
```

⚠️ This causes **any** other containers to fail connecting to the PHP container on port 9000! ⚠️

I do not know if this change was made with any clear intention or by mistake, but it seriously affected my work. _I spend hours trying to get the app running again_. Please revert this change as fast as possible or provide a proper solution to work around this issue, e.g. by binding the 9000 port on the host.

**Comment by marcosbc** [comment]
Hi @Kovah, we're looking into this and will fix it ASAP.

**Comment by marcosbc** [comment]
Update: We've created a fix, it should be available in GitHub soon. Will update when images are released.

**Comment by marcosbc** [comment]
All Debian container images were released, the rest of platforms are WIP.

Since you were using a Debian image, it should be fixed on your side.

**Comment by Kovah** [comment]
I can confirm that image version `7.2.15-debian-9-r0` is working as expected. Thank you very much for the super fast fix!

**Comment by marcosbc** [comment]
That is awesome, thanks for confirming it on your side! I'm closing this issue as the issue has been resolved.
