### ISSUE TITLE
Feature request: easier installation of ImageMagick PHP extension

### ISSUE THREAD

**Issue by jgerken** [bitnami/bitnami-docker-php-fpm#121]
**Description**

I am trying to derive a docker image from `bitnami/php-fpm:7.3-prod` which also includes, among others, ImageMagick.

To just install ImageMagick and the php extension on top of `bitnami/php-fpm:7.3-prod` you have to do:

``` Dockerfile
# install the stuff to build and install ImageMagick extension
RUN install_packages gcc make autoconf libc-dev pkg-config libmagickwand-dev && \
    # install imagick php extension and enable it 
    # At one point in the installer, a default value should be used, which
    # requires the user to press enter the echo simulates this interaction
    echo "" | pecl install imagick && \
    echo "extension=imagick.so" >> /opt/bitnami/php/etc/php.ini && \
    # remove the stuff which was required to build the extension
    apt-get -y remove --auto-remove make autoconf libc-dev pkg-config libmagickwand-dev && \
    rm -rf /usr/include/* && \
    rm -rf /tmp/*

# unfortunately imagemagick is killed, too, so reinstall it
RUN install_packages imagemagick
```

Unfortunately,  the `auto-remove` also removes ImageMagick itself, but without that options the resulting image is nearly 300MB larger compared to accidentally deinstalling it and reinstalling it afterwards. 

It would be much easier if the `bitnami/php-fpm:7.3-prod` would already provide an `imagick.so` in the `/opt/bitnami/php/lib/php/extensions` directory or provide an easy option to get a matching version installed in the directory. The file itself is only 1.3MB large so it wouldn only increase the image size by roughly 0.6%. This should be neglectable, shouldn't it?

Using this approach, a user would still have to derive from the image and install ImageMagic itself (which I wouldn't add to the base image as it is quite heavy weight) and enable it in php. So the instructions from above would be reduced to

```Dockerfile
RUN install_packages imagemagick && \
    echo "extension=imagick.so" >> /opt/bitnami/php/etc/php.ini
```

By the way, installing the Debian package `php-imagick` does not help. First, it is installed in the wrong directory, which can be corrected in the docker file. But, second, it depends on php 7.0 and not php 7.3 and is, therefore, not compatible.

If you do not want to make any changes to the image regarding ImageMagick, it would be nice if you document the way to install it. If you like you can add my snippet to the documentation - feel free to optimise it in any way.

**Comment by javsalgar** [comment]
Hi,

Thanks for the feedback. If imagick has a lot of usage, then we could consider creating a php-fpm-imagick container to cover this use case. We will evaluate which option would be better for users.

**Comment by jgerken** [comment]
Thanks for considering!

I just recognised that my install routine was flawed. I post the working one just in case someone finds this issue and tries my approach:

```Dockerfile
RUN install_packages \
      # runtime requirements for ImageMagick PHP extension
      fontconfig-config fonts-dejavu-core imagemagick-6-common \
      libfftw3-double3 libfontconfig1 libglib2.0-0 libgomp1 libjbig0 \
      liblcms2-2 liblqr-1-0 libltdl7 libmagickcore-6.q16-3 \
      libmagickwand-6.q16-3 libopenjp2-7 libtiff5 libx11-6 libx11-data libxau6 \
      libxcb1 libxdmcp6 libxext6 \
      # compile-time requirements for ImageMagick PHP extension
      gcc make autoconf libc-dev pkg-config libmagickwand-dev && \
    # Install imagick php extension and enable it 
    # At one point in the installer, a default value should be used, which
    # requires the user to press enter the echo simulates this interaction
    echo "" | pecl install imagick && \
    echo "" >> /opt/bitnami/php/etc/php.ini && \
    echo "extension=imagick.so\n[www]\nenv[MAGICK_CODER_MODULE_PATH]='/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7/modules-Q16/coders'" > /opt/bitnami/php/etc/php-fpm.d/imagemagick.conf && \
    # remove stuff which is only required for installation of ImageMagick
    apt-get -y remove --auto-remove \ 
      gcc make autoconf libc-dev pkg-config libmagickwand-dev && \
    rm -rf /usr/include/* && \
    rm -rf /tmp/* && \
```

**Comment by javsalgar** [comment]
Thanks for sharing!

**Comment by simshaun** [comment]
@jgerken Thank you very much. You saved me what I imagine would have been hours of headache.

In my case, I couldn't get the container to start and had to change this line:
```bash
echo "extension=imagick.so\n[www]\nenv[MAGICK_CODER_MODULE_PATH]='/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7/modules-Q16/coders'" > /opt/bitnami/php/etc/php-fpm.d/imagemagick.conf && \
```
to:
```bash
echo "extension=imagick\n" > /opt/bitnami/php/etc/conf.d/imagemagick.ini && \
echo "[www]\nenv[MAGICK_CODER_MODULE_PATH]='/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7/modules-Q16/coders'" > /opt/bitnami/php/etc/php-fpm.d/imagemagick.conf && \
```

**Comment by DomKrulak** [comment]
> Thanks for considering!
> 
> I just recognised that my install routine was flawed. I post the working one just in case someone finds this issue and tries my approach:
> 
> ```dockerfile
> RUN install_packages \
>       # runtime requirements for ImageMagick PHP extension
>       fontconfig-config fonts-dejavu-core imagemagick-6-common \
>       libfftw3-double3 libfontconfig1 libglib2.0-0 libgomp1 libjbig0 \
>       liblcms2-2 liblqr-1-0 libltdl7 libmagickcore-6.q16-3 \
>       libmagickwand-6.q16-3 libopenjp2-7 libtiff5 libx11-6 libx11-data libxau6 \
>       libxcb1 libxdmcp6 libxext6 \
>       # compile-time requirements for ImageMagick PHP extension
>       gcc make autoconf libc-dev pkg-config libmagickwand-dev && \
>     # Install imagick php extension and enable it 
>     # At one point in the installer, a default value should be used, which
>     # requires the user to press enter the echo simulates this interaction
>     echo "" | pecl install imagick && \
>     echo "" >> /opt/bitnami/php/etc/php.ini && \
>     echo "extension=imagick.so\n[www]\nenv[MAGICK_CODER_MODULE_PATH]='/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7/modules-Q16/coders'" > /opt/bitnami/php/etc/php-fpm.d/imagemagick.conf && \
>     # remove stuff which is only required for installation of ImageMagick
>     apt-get -y remove --auto-remove \ 
>       gcc make autoconf libc-dev pkg-config libmagickwand-dev && \
>     rm -rf /usr/include/* && \
>     rm -rf /tmp/* && \
> ```

Last line gives this
[WARNING]: Empty continuation lines will become errors in a future release.

Just take `&& \` off and warning should disappear.

**Comment by javsalgar** [comment]
I'm reopening the issue so it is tracked. If we have news about a php-fpm with image magick I'll update the ticket.

**Comment by jgerken** [comment]
`bitnami/php-fpm` has changed from Debian 9 to Debian 10 as base image, therefore the installation approach given in my description does not work any longer. Have not yet figured out how to do this on the latest version of the base image.

**Comment by DomKrulak** [comment]
You just need to change versions of some packages so they're compatible with the Debian 10's packages. 
```
# Install additional extensions
RUN install_packages \
    # Runtime requirements for ImageMagick PHP extension.
    fontconfig-config fonts-dejavu-core imagemagick-6-common \
    libfftw3-double3 libfontconfig1 libglib2.0-0 libgomp1 libjbig0 \
    liblcms2-2 liblqr-1-0 libltdl7 libmagickcore-6.q16-6 \
    libmagickwand-6.q16-6 libopenjp2-7 libtiff5 libx11-6 libx11-data libxau6 \
    libxcb1 libxdmcp6 libxext6 unzip \
    # Compile-time requirements for ImageMagick PHP extension.
    gcc make autoconf libc-dev pkg-config libmagickwand-dev \
    # Install imagick php extension and enable it
    # At one point in the installer, a default value should be used, which
    # requires the user to press enter the echo simulates this interaction
    echo "" | pecl install redis imagick
```

**Comment by javsalgar** [comment]
Hi,

Thanks for the information @DomKrulak :)

**Comment by robots4life** [comment]
Any news on this?

**Comment by javsalgar** [comment]
Hi,

So far, it is not in our long-term plans to create a php-fpm-imagick image. Would creating your fork like the OP showed work in the meantime?
