### ISSUE TITLE
No logs from php-fpm container

### ISSUE THREAD

**Issue by zz80** [bitnami/bitnami-docker-php-fpm#122]
**Description**

No logs from the container

**Steps to reproduce the issue:**

docker run bitnami/php-fpm:7.3-ol-7 

**Describe the results you received:**
NOTHING

**Version**

- Output of `docker version`:

```
Docker version 18.06.1-ce, build e68fc7a
```

- Output of `docker info`:

```
Containers: 40
 Running: 2
 Paused: 0
 Stopped: 38
Images: 294
Server Version: 18.06.1-ce
Storage Driver: aufs
 Root Dir: /var/snap/docker/common/var-lib-docker/aufs
 Backing Filesystem: extfs
 Dirs: 359
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 468a545b9edcd5932818eb9de8e72413e616e86e
runc version: N/A (expected: 69663f0bd4b60df09991c08812a60108003fa340)
init version: 949e6fa (expected: fec3683)
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.18.0-17-generic
Operating System: Ubuntu Core 16
OSType: linux
Architecture: x86_64
CPUs: 12
Total Memory: 15.32GiB
Name: salvo-xps
ID: 7VQO:DCSR:I2NB:QXWH:E3WH:EFSF:RSAI:D5AT:MCQW:IUPM:X7DY:NUR4
Docker Root Dir: /var/snap/docker/common/var-lib-docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 61
 Goroutines: 96
 System Time: 2019-04-24T16:06:22.762848298+02:00
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

**Comment by javsalgar** [comment]
Hi,

Did you try it with a custom php application that should provide any logging?

**Comment by clalbus** [comment]
Could it be due to `/opt/bitnami/php/etc/php-fpm.conf` having the following configuration?

```php
error_log = /opt/bitnami/php/logs/php-fpm.log
```

Furthermore:
```bash
root@app:/opt/bitnami/php/etc# ls -l /proc/1/fd
total 0
lrwx------ 1 root root 64 May  2 09:41 0 -> /dev/null
lrwx------ 1 root root 64 May  2 09:41 1 -> /dev/null
l-wx------ 1 root root 64 May  2 09:41 2 -> /opt/bitnami/php/logs/php-fpm.log
```

It seems to me that php-fpm logs are never redirected to stderr.

**Comment by andresbono** [comment]
Hi @clalbus, thanks for the information. Are you faciing the same issue? Are you trying _php-fpm_ with a custom application and a webserver to serve it?

**Comment by andresbono** [comment]
Hi again @clalbus, @zz80, we have tried nginx + php-fpm container and most of the messages are logged by the nginx container. For instance, errors in the php syntax are also reported through nginx logs.

**Comment by clalbus** [comment]
Hi @andresbono,

Thank you for your response. I was trying to symlink /dev/stderr to my application log (inspired by similar solution in Nginx container), hence my comment above.

After your last comments, I have realized that it is designed to work this way with bitnami/php-fpm. I have reconfigured my PHP framework to log out to stderr and can confirm that it solves my problem.

Thanks again.

**Comment by andresbono** [comment]
Great to hear, @clalbus!!
