### ISSUE TITLE
in example, the vhosts folder should be server_blocks

### ISSUE THREAD

**Issue by dgmdevelopment** [bitnami/bitnami-docker-php-fpm#123]
**Description**

ERROR ==> Custom server blocks files were found inside '/bitnami/nginx/conf/vhosts'. This configuration is not supported anymore. Please mount your custom server blocks config files at '/opt/bitnami/nginx/conf/server_blocks' instead.

**Steps to reproduce the issue:**

1. docker-compose up 
(using updated version of nginx)

Just passing on. Hope it helps!

**Comment by andresbono** [comment]
Thanks for reporting it, @dgmdevelopment!!

**Comment by aaden001** [comment]
I am currently getting this issue how can i resolve it ?

**Comment by Mauraza** [comment]
Hi @aaden001, 

Could you add more information about the error are you getting?
