### ISSUE TITLE
docker-php-ext-install  command not found

### ISSUE THREAD

**Issue by zyy314680012** [bitnami/bitnami-docker-php-fpm#125]
can intall "docker-php-ext-install" ?

**Comment by andresbono** [comment]
Hi @zyy314680012 that is a helper script from Docker official image, see https://docs.docker.com/samples/library/php/#how-to-install-more-php-extensions.

Are you trying to install an extension?

**Comment by zyy314680012** [comment]
thank you

**Comment by DurandSacha** [comment]
I used 
`RUN apt -yqq update
RUN apt-get install -y php php-fpm php-pdo-mysql php-mbstring php-mysqli`

**Comment by rafariossaa** [comment]
Hi,
  @DurandSacha have into account that in this container php is not installed through system packages.
