### ISSUE TITLE
using xdebug with bitnami-php-fpm-5.6 container

### ISSUE THREAD

**Issue by richb201** [bitnami/bitnami-docker-php-fpm#128]
I have tried using the Dockerfile for adding xdebug to  php 7.2. Thank you. I am however using php 5.6. When I try to image build a new container using the Dockerfile supplied by tompizmor (as you suggested), I get a bunch of errors (see below) due to the version of php-fpm.  I have already modified the Dockerfile to use 5.6. but I don't know what to do with the errors below. 

pecl/igbinary requires PHP (version >= 7.0.0), installed version is 5.6.34
pecl/memcached requires PHP (version >= 7.0.0), installed version is 5.6.34
pecl/memcached can optionally use PHP extension "igbinary" (version >= 2.0)
pecl/memcached can optionally use PHP extension "msgpack" (version >= 2.0)
pecl/msgpack requires PHP (version >= 7.0.0), installed version is 5.6.34
pecl/redis requires PHP (version >= 7.0.0, version <= 7.9.99), installed version is 5.6.34
pecl/xdebug requires PHP (version >= 7.0.0), installed version is 5.6.34
downloading PDO_DBLIB-1.0.tgz ...

**Comment by juan131** [comment]
Hi @richb201 

Please let me warn you about using **PHP 5.6**, please note we're not maintaining this branch anymore (check the link below) since PHP stopped maintaining this branch as you can see on this [link](https://www.php.net/supported-versions.php): 

- https://github.com/bitnami/bitnami-docker-php-fpm#supported-tags-and-respective-dockerfile-links

In the Gist below, you can find a "generic" solution provided by a Bitnami user to install a set of extensions on top of the Bitnami PHP-FPM Docker image:

- https://gist.github.com/rquadling/53fd99994d653b0a1b88f4a0705ae655

**Comment by richb201** [comment]
Juan, that gist was the one I tried. It comes up with errors that are due to the version. So the note at the bottom about it working for php 5.6  r-2 is in error. My previous post shows the errors and they all seem to be version related. 

So, can I build with a non-Bitnami 5.6? Can you post the 5.6 Dockerfile so I can at least see what you guys are adding in? 

OR

Does the mod you guys made to allow users to use our own php.ini at runtime also not work? I really need some support here.

On October 22, 2019, at 03:38, Juan Ariza Toledano <notifications@github.com> wrote:

Hi @richb201

Please let me warn you about using PHP 5.6, please note we're not maintaining this branch anymore (check the link below) since PHP stopped maintaining this branch as you can see on this link:

https://github.com/bitnami/bitnami-docker-php-fpm#supported-tags-and-respective-dockerfile-links 

In the Gist below, you can find a "generic" solution provided by a Bitnami user to install a set of extensions on top of the Bitnami PHP-FPM Docker image:

https://gist.github.com/rquadling/53fd99994d653b0a1b88f4a0705ae655 

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.￼

[ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/bitnami/bitnami-docker-php-fpm/issues/128?email_source=notifications">https://github.com/bitnami/bitnami-docker-php-fpm/issues/128?email_source=notifications</a>\u0026email_token=ABVBHGIYA54KT7V2346DPB3QP2UWNA5CNFSM4JC4ODE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB4Z4YY#issuecomment-544841315", "url": "<a href="https://github.com/bitnami/bitnami-docker-php-fpm/issues/128?email_source=notifications">https://github.com/bitnami/bitnami-docker-php-fpm/issues/128?email_source=notifications</a>\u0026email_token=ABVBHGIYA54KT7V2346DPB3QP2UWNA5CNFSM4JC4ODE2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEB4Z4YY#issuecomment-544841315", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } } ]

**Comment by juan131** [comment]
Hi @richb201 

>  Can you post the 5.6 Dockerfile so I can at least see what you guys are adding in?

The Dockerfile (and the rest of files) used to build the image in the **5.6 branch** were removed in the commit below:

- https://github.com/bitnami/bitnami-docker-php-fpm/commit/7ecc28c4968ad6ab30d11ad972cdc80c55331868

You can find all the files there.

**Comment by richb201** [comment]
Juan, I just changed the references to 7.2 to 5.6. That was it. And I just
deleted the direc where I was doing the build too. I am going to try to
update my app to use 7.2.

**Comment by richb201** [comment]
Hey Juan. I managed to get my AMP development environment on Docker with the help of a consultant. But I am still having a few issues. First is my need to move my application out of the document root for security. I am using codeigniter and there is a setting in index.php for where the application is located. $application_folder='application'. So I have tried moving the application folder above the root and i use the absolute full server path. So I set it to '/opt/docker-substantiator/application' and type localhost in the browser and I get "Your application folder path does not appear to be set correctly. Please open the following file and correct: index.php".
I am also having trouble connecting to the database. I was under the impression to use the name of the container as the host, but I need to do more research on this. If I could just set the application directory correctly, that would be a little "win".

**Comment by juan131** [comment]
Hi @richb201 

> I managed to get my AMP development environment on Docker with the help of a consultant.

Great! I'm glad you managed to get it done.

> First is my need to move my application out of the document root for security. I am using codeigniter and there is a setting in index.php for where the application is located. $application_folder='application'. So I have tried moving the application folder above the root and i use the absolute full server path. So I set it to '/opt/docker-substantiator/application' and type localhost in the browser and I get "Your application folder path does not appear to be set correctly. Please open the following file and correct: index.php".

I'm not an expert on Codeigniter but I guess it's complaining since you're configuring a path in the `$application_folder` setting but your application code is located on a different one. So please doublecheck they're synced.
