### ISSUE TITLE
Image for PHP 7.4

### ISSUE THREAD

**Issue by Kovah** [bitnami/bitnami-docker-php-fpm#130]
Hi,

I just wanted to ask if a new image for PHP 7.4 is already planned, and if yes, when it might become available? If it's not planned I would like to request it, as I really like working with your images.

Thank you,
Kevin

**Comment by jotamartos** [comment]
Hi @Kovah,

Thank you for your interest. I want to let you know that the team is currently working on generating the new images with PHP 7.4. I can't provide you with an exact date but that new version should be available by the end of next week or so. 

Please stay tuned :)

**Comment by Lucky-Loek** [comment]
Cheers!

![afbeelding](https://user-images.githubusercontent.com/9716643/71083865-4d101f00-2194-11ea-99a5-63f36d0a3d5a.png)

**Comment by Kovah** [comment]
Was Pecl removed from the 7.4 image? My Docker build processes throws errors about it.

**Comment by lahaxearnaud** [comment]
Hello,

Git and zip also disappear from 7.3, it's currently not possible to use composer with the 7.4 image.
Is it on purpose ?

Arnaud

**Comment by miguelaeh** [comment]
Hi,
We are checking it, it seems that `pecl` has not been shipped into the image, we are investigating why, we will release a new version with it.
Regarding `git` and `zip` it seems they have never been shipped into the image. But PHP is compiled with the option `--enable-zip` in the configure.
Thank you very much for reporting the issue!!!

**Comment by miguelaeh** [comment]
Hi again,
We found the issue and we are releasing a new image that contains `pecl`. It is already available on github, and it will be also available on dockerhub soon.

From the PHP docs:
```
PECL is a repository of PHP extensions that are made available to you via the PEAR packaging system.
```
So it was necessary to add to the compilation the flag `--with-pear`.

We checked again the issue with `composer` and as it seems that depends on Git, so we will also add Git to our PHP images.

Again, thank you for reporting the issue.
Regards.

**Comment by Kovah** [comment]
> But PHP is compiled with the option --enable-zip in the configure.

Hm. There seems to be something wrong or missing I think. When I install packages via composer, it fails with the error "Update failed (The zip extension and unzip command are both missing, skipping."
I fetched the newest image with the ID `5da3d136a31d`, but the Zip extension is not installed and thus cannot be enabled. The following php -i output is present in the 7.3, but missing in 7.4:
```
zip
Libzip version => 1.1.2
```

**Comment by sameersbn** [comment]
@miguelaeh My guess is that `--enable-zip` did not really enable gzip support due to missing `libzip-dev` build dependency.

**Comment by miguelaeh** [comment]
Hi @Kovah ,
We addressed some changes in the compilation and now it seems to be correct. The new version is being tested, so it should be published soon.
Let us know when you have the chance if it worked. 
Thank you very much.
Regards.

**Comment by miguelaeh** [comment]
Hi again,
After an investigation, we decided to not support `libzip` for PHP 7.4 in our `oracle-linux` container. This is because of the PHP 7.4 compilation needs a `libzip` version greater than `0.11`, while the versions on the official repository for that distro is `0.10`. However, the `debian` container will ship it with the correct version, as the official repository has the desired version `0.11`.
