### ISSUE TITLE
Unable to enable sodium in php 7.3

### ISSUE THREAD

**Issue by smartmarketingreports** [bitnami/bitnami-docker-php-fpm#135]
I'm trying to use bitnami/php-fpm:7.3-prod. I like the small size of the image.
I believe that sodium ought to be present in php 7.3+. However when i run a PHP application that is dependent on this library it fails. I've found the libsodium23 binary for debian10 and can install that - I haven't found a way to enable sodium support in the PHP 7.3 though.
It works on php:7.3.18-fpm-buster - but that image is 100MB larger which isn't justified by the sodium library alone.
Could you please advise?
Thanks

**Comment by carrodher** [comment]
Hi, Bitnami provides two images with php-fpm 7.3: `bitnami/php-fpm:7.3` and `bitnami/php-fpm:7.3-prod`

Containers tagged `prod` are production containers based on [minideb](https://github.com/bitnami/minideb). They contain the minimal dependencies required by an application to work.

They don't include development dependencies, so they are commonly used in multi-stage builds as the target image. Application code and dependencies should be copied from a different container.

The resultant containers only contain the necessary pieces of software to run the application. Therefore, they are smaller and safer (fewer packages, less chance of vulnerabilities). You can learn how to use multi-stage builds to build your production application container in the [example](https://github.com/bitnami/bitnami-docker-php-fpm/blob/master/example) directory; you can follow this approach and install the required binary.

Here is the comparasion in terms of size and updates frequency between the Bitnami images and the one you mentioned:
```console
$ docker images
REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
bitnami/php-fpm                7.3-prod            87c63736cdcf        14 hours ago        274MB
bitnami/php-fpm                7.3                 b87e4e033076        14 hours ago        310MB
php                            7.3.18-fpm-buster   c227f809a744        2 weeks ago         398MB
```

**Comment by smartmarketingreports** [comment]
Hi carrodher,
The idea of minimum dependencies is good. My point is that sodium support is supposed to be a core element of php 7.3. So why does it appear to be missing from the bitnami images? To me that means that what bitnami states to be php 7.3 isn't...
Cheers

> Hi, Bitnami provides two images with php-fpm 7.3: `bitnami/php-fpm:7.3` and `bitnami/php-fpm:7.3-prod`
> 
> Containers tagged `prod` are production containers based on [minideb](https://github.com/bitnami/minideb). They contain the minimal dependencies required by an application to work.
> 
> They don't include development dependencies, so they are commonly used in multi-stage builds as the target image. Application code and dependencies should be copied from a different container.
> 
> The resultant containers only contain the necessary pieces of software to run the application. Therefore, they are smaller and safer (fewer packages, less chance of vulnerabilities). You can learn how to use multi-stage builds to build your production application container in the [example](https://github.com/bitnami/bitnami-docker-php-fpm/blob/master/example) directory; you can follow this approach and install the required binary.
> 
> Here is the comparasion in terms of size and updates frequency between the Bitnami images and the one you mentioned:
> 
> ```
> $ docker images
> REPOSITORY                     TAG                 IMAGE ID            CREATED             SIZE
> bitnami/php-fpm                7.3-prod            87c63736cdcf        14 hours ago        274MB
> bitnami/php-fpm                7.3                 b87e4e033076        14 hours ago        310MB
> php                            7.3.18-fpm-buster   c227f809a744        2 weeks ago         398MB
> ```

**Comment by carrodher** [comment]
Hi, as far as I know, [Sodium](https://www.php.net/manual/en/book.sodium.php) is a cryptographic extension like OpenSSL, Mcrypt or Cracklib, those extensions can be added to PHP but they are not included as part of PHP itself, so we are adding some of them by default in the images, but we can't add all the existing extensions, we are used to evaluating that additions based on users' feedback.

In this case, I just created an internal task to evaluate the addition of Sodium by default, but as this is not a critical issue I can't provide an exact ETA for this task.

**Comment by smartmarketingreports** [comment]
Hi,
Agreed - Sodium is very much a cryptographic library... However the intention from 7.2.0 onwards is that it is part of the PHP core. Not additions.
For example [https://www.php.net/manual/en/sodium.installation.php](https://www.php.net/manual/en/sodium.installation.php) As of PHP 7.2.0 this extension is bundled with PHP. For older PHP versions this extension is available via PECL.
[https://www.zend.com/blog/libsodium-and-php-encrypt](https://www.zend.com/blog/libsodium-and-php-encrypt) also says Developers can use Sodium for PHP encryption and decryption with PHP 7.2 and newer without an extension. If you want to use Sodium with PHP 7.0 or 7.1, you need to install a PECL extension.
> Hi, as far as I know, [Sodium](https://www.php.net/manual/en/book.sodium.php) is a cryptographic extension like OpenSSL, Mcrypt or Cracklib, those extensions can be added to PHP but they are not included as part of PHP itself, so we are adding some of them by default in the images, but we can't add all the existing extensions, we are used to evaluating that additions based on users' feedback.
> 
> In this case, I just created an internal task to evaluate the addition of Sodium by default, but as this is not a critical issue I can't provide an exact ETA for this task.

**Comment by carrodher** [comment]
Yes, sorry, what I mean with _"they are not included as part of PHP itself"_ it's that we need to do some changes on our side to support it like changing the compilation, testing it in the different distros, etc; as opposed to other features that are added to the core and work out-of-the-box with zero changes, just releasing a new version.

In this case, as we need to check different things I created the task to evaluate those aspects.

**Comment by carrodher** [comment]
I just set the on-hold tag to prevent stale bot closing this issue as there is a task in our backlog to investigate it

**Comment by carrodher** [comment]
In order to unify the approaches followed in Bitnami containers and Bitnami charts, we are moving some issues in `bitnami/bitnami-docker-<container>` repositories to `bitnami/containers`. Please follow [bitnami/containers](https://github.com/bitnami/containers) to keep you updated about the latest bitnami images.

If this issue is still applicable, please feel free to recreate it at https://github.com/bitnami/containers/issues/new/choose

More information here: https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html
