### ISSUE TITLE
Does this image support to connect to php through unix socket file

### ISSUE THREAD

**Issue by huynq2007** [bitnami/bitnami-docker-php-fpm#136]
Instead of using

```
fastcgi_pass phpfpm:9000;
```

I would like to use socket file like this:
```
fastcgi_pass unix:/var/run/php-fpm.sock;
```
Do I need to configure something?

**Comment by jotamartos** [comment]
Hi @huynq2007 ,

That option is not available by default in the container. However, you can update the PHP-FPM's configuration file 

```
/opt/bitnami/php/etc/php-fpm.d/www.conf
```

and set the socket to use in the listen parameter 

```
listen = /opt/bitnami/php/var/run/www.sock
```

After that, you will need to restart the container for the changes to take effect. 

I hope this helps

**Comment by huynq2007** [comment]
@jotamartos 
Thank you. I have sorted it out.
