### ISSUE TITLE
enable semaphore in php-fpm

### ISSUE THREAD

**Issue by prakashlts** [bitnami/bitnami-docker-php-fpm#137]
I am trying to build **php-fpm:latest** docker image. Everything is working fine. 

But I am getting an error in one place, where I am using the PHP semaphore function.

my code is:- 
`$semaphore1 = sem_get($key, $maxAcquire, $permissions, $autoRelease);`

getting an error:- 
`Call to undefined function sem_get()`

This code is working with the **php-apache** docker image. Only getting error in this image.

I tried many solutions but nothing works, please let me know how can I solve this error.

**Comment by dani8art** [comment]
Hi @prakashlts, thanks for posting the issue. It seems those extensions are included by default in mod_php but not in php-fpm. In this specific case, we would evaluate to check if those extensions are safe to enable them by default as there is no way to add them as shared modules or dependencies. This could take some time on our side as we are a small team and this is a very specific request changing the default options.
