### ISSUE TITLE
How to set clear_env = no for php-fpm?

### ISSUE THREAD

**Issue by 4n70w4** [bitnami/bitnami-docker-php-fpm#139]
Hi! I want add `clear_env = no` to php-fpm confuguration. I found in file `/opt/bitnami/php/etc/php-fpm.d/www.conf` commented line:

```
;clear_env = no
```

But I have no idea how to override this value inside the container without rebuilding the image.
Go every once in a container and manually override - also not a good idea.

Overwriting the entire file via volume is also not very convenient, in new versions of php the configuration may change, and you will have to manually synchronize the configuration between versions.

Is there any best practice for this?

**Comment by juan131** [comment]
Hi @4n70w4 

Please take a look to the link below where it's explained how to add custom ini files, so you can customize your PHP configuration:

- https://github.com/bitnami/bitnami-docker-php-fpm#add-additional-ini-files

**Comment by 4n70w4** [comment]
@juan131 but `/opt/bitnami/php/etc/conf.d/` is php configuration, is not php-fpm pool configuration.

**Comment by juan131** [comment]
Hi @4n70w4 

As you can see in the PHP-FPM configuration file, it also allows dynamic loading configuration from the `/opt/bitnami/php/etc/php-fpm.d/` directory:

```
$ cat /opt/bitnami/php/etc/php-fpm.conf
...
include=/opt/bitnami/php/etc/php-fpm.d/*.conf
```

Therefore, you can also mount a custom `.conf` file at `/opt/bitnami/php/etc/php-fpm.d/` directory, and the configuration will be considered. E.g.:

```
$ docker run -it -v /path/to/custom.conf:/opt/bitnami/php/etc/php-fpm.d/custom.conf bitnami/php-fpm
```
