### ISSUE TITLE
how to install extensions...

### ISSUE THREAD

**Issue by EddyLee1010** [bitnami/bitnami-docker-php-fpm#141]
thanks

**Comment by FraPazGal** [comment]
Hello @EddyLee1010,

That would depend on whether the extension is installed but disabled by default or you also need to install it. The current list of extensions we package in our container is the following:

```
./lib/php/extensions/pdo_pgsql.so
./lib/php/extensions/pdo_dblib.so
./lib/php/extensions/mongodb.so
./lib/php/extensions/imagick.so
./lib/php/extensions/mcrypt.so
./lib/php/extensions/memcached.so
./lib/php/extensions/xdebug.so
./lib/php/extensions/apcu.so
./lib/php/extensions/opcache.so
./lib/php/extensions/maxminddb.so
./lib/php/extensions/pgsql.so
```

Some of them may be disabled, in which case you just need to enable them modifying the `php.ini` file at `/opt/bitnami/php/etc/php.ini`.

If the extension you need is not in that list, you would need you download the `.so` file and add it to the `extensions` folder and enable it in `php.ini`. You can see an example of how to customise one of our container images [here](https://github.com/bitnami/bitnami-docker-mariadb#customize-this-image).
