### ISSUE TITLE
passing in environment variables

### ISSUE THREAD

**Issue by richb201** [bitnami/bitnami-docker-php-fpm#143]
I am using bitnami php-fpm 7.2 docker image.  I need to pass in some credentials via env variables so I can get them to access AWS Secrets. How can I set env variables from my .env file through docker-compose, and to me php application? Is there some example?

**Comment by miguelaeh** [comment]
Hi @richb201 ,
Try with this: https://docs.docker.com/compose/environment-variables/#the-env_file-configuration-option
