### ISSUE TITLE
Why is there no redis extension for this php 7.4?

### ISSUE THREAD

**Issue by ellermister** [bitnami/bitnami-docker-php-fpm#155]
**Description**

Why is there no redis extension for this php 7.4?

**Steps to reproduce the issue:**

`php -m|grep redis`

**Describe the results you received:**
(empty)

**Describe the results you expected:**
redis

**Additional information you deem important (e.g. issue happens only occasionally, environment details, etc.):**
`docker run --rm -it phpfpm:7.4 php -m|grep redis`

**Comment by javsalgar** [comment]
Hi,

Thanks for the input! We wanted to limit the number of php extensions in order to maintain the container size. I will forward this request to the engineering team for evaluation. 

Thanks again for the feedback!

**Comment by ynwcel** [comment]
use this `Dockerfile` and build yourself image
```Dockerfile
FROM bitnami/php-fpm:7.4
RUN install_packages gcc make autoconf libc-dev pkg-config && \
    echo "" | pecl install redis && \
    echo "extension=redis.so\n" > /opt/bitnami/php/etc/conf.d/redis.ini && \
    apt-get -y remove --auto-remove gcc make autoconf libc-dev pkg-config && \
    rm -rf /usr/include/* && \
    rm -rf /tmp/*
```
