### ISSUE TITLE
[help needed] Possible to publish several websites using the same container?

### ISSUE THREAD

**Issue by asitemade4u** [bitnami/bitnami-docker-php-fpm#157]
I would like to publish several websites (for our internal use) using the same docker container.

Is that even possible? Or shall I multiply the docker PHP-FPM stacks?

If it is possible, would you kindly direct me to additional documentation or give me the process to follow ad the content of the needed files:

- nginx server blocks for both websites
- `docker-compose.yml`
- `php-fpm.conf`

Thanks.
S.

**Comment by juan131** [comment]
It seems it is not an issue related to the Bitnami container image but about how the application or environment is being used/configured.

For information regarding the application itself, customization of the content within the application, or questions about the use of technology or infrastructure; we highly recommend checking forums and user guides made available by the project behind the application or the technology.

That said, I will keep this ticket open until the stale bot closes it just in case someone from the community adds some valuable info.
