### ISSUE TITLE
image bitnami/php-fpm:7.4

### ISSUE THREAD

**Issue by edward-jw-yu** [bitnami/bitnami-docker-php-fpm#158]
### Name and Version

bitnami/php-fpm:7.4

### What steps will reproduce the bug?

Too Bad!!!
There are Mining programs in the image bitnami/php-fpm:7.4

### What is the expected behavior?

the Mining programs are /tmp/kinsing and /tmp/kdevtmpfsi

### What do you see instead?

the Mining programs are /tmp/kinsing and /tmp/kdevtmpfsi

### Additional information

the Mining programs are /tmp/kinsing and /tmp/kdevtmpfsi

**Comment by carrodher** [comment]
I just deployed the bitnami/php-fpm:7.4 container and there are not any of the mentioned directories in the `/tmp` folder:

```console
$ docker ps
CONTAINER ID   IMAGE                 COMMAND                  CREATED         STATUS         PORTS                    NAMES
497c2e11046b   bitnami/php-fpm:7.4   "php-fpm -F --pid /o…"   7 seconds ago   Up 4 seconds   0.0.0.0:9000->9000/tcp   bitnami-docker-php-fpm_php_1

$ dcexec 497c2e11046b
root@497c2e11046b:/app# ls -la /tmp/
total 12
drwxrwxrwt 1 root root 4096 Feb 27 16:31 .
drwxr-xr-x 1 root root 4096 Feb 27 16:31 ..
drwxr-xr-x 3 root root 4096 Feb 27 13:19 bitnami
```
