### ISSUE TITLE
php.ini values not being added.

### ISSUE THREAD

**Issue by fiveanddone** [bitnami/bitnami-docker-php-fpm#18]
I'm trying to enable xdebug extension.

I'm adding the following to my local php-fpm.conf file

```
php_admin_value[zend_extension]="/opt/bitnami/php/lib/php/extensions/xdebug.so"
php_admin_flag[xdebug.remote_enable]=true
php_admin_value[xdebug.remote_port]=9001
php_admin_flag[xdebug.remote_autostart]=1
php_admin_flag[xdebug.remote_connect_back]=1
php_admin_value[xdebug.remote_handler]=dbgp
```

Php info does not show xdebug was loaded.  Is it possible to expose the php.ini file?

**Comment by chipironcin** [comment]
Hi @fiveanddone 
Additional php.ini defines specified in the `php-fpm.conf` file will only be applied to workers in the php-fpm pool.
Executing the `php` command will only take the options from `php.ini` file.

If you want to globally enable XDebug you can uncomment lines under `XDebug` section in `php.ini` file.
If you want to enable XDebug only for the spawned workers from php-fpm, your configuration should work with those workers.

I agree exposing `php.ini` would be useful for this image.
You can expose it by applying the following patch and rebuilding the image.

```
diff --git a/post-install.sh b/post-install.sh
index d8a7200..48ff4be 100644
--- a/post-install.sh
+++ b/post-install.sh
@@ -5,10 +5,13 @@ mkdir $BITNAMI_APP_DIR/etc/conf.defaults
 mkdir $BITNAMI_APP_DIR/etc/conf
 mv $BITNAMI_APP_DIR/etc/php-fpm.conf $BITNAMI_APP_DIR/etc/conf.defaults
 ln -s $BITNAMI_APP_DIR/etc/conf/php-fpm.conf $BITNAMI_APP_DIR/etc/php-fpm.conf
+cp $BITNAMI_APP_DIR/etc/php.ini $BITNAMI_APP_DIR/etc/conf.defaults
+mv $BITNAMI_APP_DIR/etc/php.ini $BITNAMI_APP_DIR/etc/conf
+ln -s $BITNAMI_APP_DIR/etc/conf/php.ini $BITNAMI_APP_DIR/etc/php.ini

 chown -R $BITNAMI_APP_USER:$BITNAMI_APP_USER /app/ $BITNAMI_APP_DIR/etc/conf $BITNAMI_APP_DIR/var/log
 ln -s $BITNAMI_APP_DIR/var/log $BITNAMI_APP_VOL_PREFIX/logs
 ln -s $BITNAMI_APP_DIR/etc/conf $BITNAMI_APP_VOL_PREFIX/conf

 # Temp fix for disabling php-fpm caching
-sudo sed -i -e 's/\(opcache\.enable=\)1/\10/g' $BITNAMI_PREFIX/php/etc/php.ini
+sudo sed --follow-symlinks -i -e 's/\(opcache\.enable=\)1/\10/g' $BITNAMI_PREFIX/php/etc/php.ini
```

Do not forget restarting the container to apply your changes in the conf files.
I have already opened a PR with this change. [https://github.com/bitnami/bitnami-docker-php-fpm/pull/21]

Thanks for testing our images and suggest improvements. If you find more issues feel free to open a new issue or creating a Pull Request :)

**Comment by prydonius** [comment]
#21 has just been merged, it will be pushed to DockerHub with the `5.5.30-0-r01` tag shortly.

**Comment by fiveanddone** [comment]
It's working now, thank you
