### ISSUE TITLE
failed to enable imagick extension

### ISSUE THREAD

**Issue by chekun** [bitnami/bitnami-docker-php-fpm#26]
i tried to enable imagick extension under following steps:

1. apt-get update
2. apt-get install imagemagick
3. uncomment imagick extension in php.ini
4. restart container

```
<?php

$image = new Imagick('images/cover.png');
``` 

throws exception says 

```
Fatal error: Uncaught exception 'ImagickException' with message 'no decode delegate for this image format `images/cover.png' @ error/constitute.c/ReadImage/544' in /app/public/test.php:3 Stack trace: #0 /app/public/test.php(3): Imagick->__construct('images/cover.pn...') #1 {main} thrown in /app/public/test.php on line 3
```

Why is that?

**Comment by chipironcin** [comment]
Hi @chekun 
We ship ImageMagick by default in all our PHP Stacks like LAMP.
In order to reduce the size of this container, we skipped ImageMagick but you can easily include it following these steps:

```
sudo apt-get update
sudo apt-get install libmagickwand-dev
wget https://pecl.php.net/get/imagick-3.1.2.tgz
tar -zxvf imagick-3.1.2.tgz
cd imagick-3.1.2
phpize
export CFLAGS="$CFLAGS -I/usr/include/ImageMagick"
./configure
#Substitute CFLAGS option in Makefile for the following line
#CFLAGS = -I/opt/bitnami/common/include -I/usr/include/ImageMagick
make
sudo make install
# Uncomment Imagemagick extension from php.ini file
```

Tell me if this worked for you :)

**Comment by chekun** [comment]
@chipironcin Thanks .

I struggled to achieve this following these steps.

```
apt-get install imagemagick
```

in docker-compose.yml

```
phpfpm:
    environment:
        - MAGICK_HOME=/usr/lib/x86_64-linux-gnu/ImageMagick-6.7.7/
        - MAGICK_CONFIGURE_PATH=/etc/ImageMagick/
        - MAGICK_CODER_MODULE_PATH=/usr/lib/x86_64-linux-gnu/ImageMagick-6.7.7/modules-Q16/coders
```

Add these threee envs solved my problem.

Again, thanks for you guys' great work.

**Comment by chipironcin** [comment]
Glad you were able to address it.
Also your solution is cleaner than mine and avoid compiling again the module.
This is something we will document soon. Thanks for reporting it and give a solution.

Do not hesitate in opening new issues if you spot one and feel free to open PR too.
