### ISSUE TITLE
install custom php modules

### ISSUE THREAD

**Issue by zeroasterisk** [bitnami/bitnami-docker-php-fpm#30]
I see in this closed issue some notes on how to install custom php modules:
https://github.com/bitnami/bitnami-docker-php-fpm/issues/26#issuecomment-160151561
- Can you provide more information on where we would do that?
- Can you show me what modules are already included?  (I can't find the install scripts)

thanks!

I really like most of what's going on here, with you suite of images, but I just don't see how to easily extend/customize beyond at runtime.

**Comment by prydonius** [comment]
Hey @zeroasterisk,

> Can you provide more information on where we would do that?

We bundle the most common extensions out-of-the-box, so you should be good unless you need to install something specific. What's your use-case?

You can find more info on how to install some other modules in our wiki (though you may need to adapt some of the commands for the container): https://wiki.bitnami.com/Components/PHP

> Can you show me what modules are already included? (I can't find the install scripts)

You can check the enabled modules by running `docker run --rm bitnami/php-fpm php -m`. You can also find some shared extensions you can enable in `/opt/bitnami/php/lib/php/extensions`.

Thank you for the feedback! Do you have any ideas on how we could make the containers more customisable?

**Comment by zeroasterisk** [comment]
Thanks!  

I really like a lot of what you've got going on, and the readme has excellent setup / startup documentation at just the right level.  Kudos!

The "missing PHP modules" I was looking for were for things like xcache or newrelic... I see in your wiki links, you've got instructions on how to implement on a running machine/container... but I'd want to bake that into the image and re-use... 

My goal here is to end up with "standard" images, with my own customizations as needed, which could interoperate with your already existing suite of other containers in a reliable and documented manner.  

To that end, should I just make my own Dockerfile FROM yours, and add whatever extra stuff I want to that?

**Comment by prydonius** [comment]
Sorry for the delay. Using this image as a base is a good solution.

If you publish your images on Docker Hub as automated builds, you can set it up to link to this repository, so that as this is updated, your image is automatically rebuilt.

Alternatively, you may want to check out [Bitnami Stacksmith](https://stacksmith.bitnami.com/), this service will allow you to create a PHP container and subscribe to version updates via webhook to integrate with your CI. Currently the Stacksmith generated PHP differs to this one, e.g. not running PHP-FPM by default, however it will give you more freedom over build time customisation.

Hope this helps. Merry Christmas and a Happy New Year!

**Comment by FrodeMMeling** [comment]
I am trying to install memcached extension. How to do this?

**Comment by silviofdez** [comment]
We bundle the most common extensions out-of-the-box, so you should be good unless you need to install something specific. What's your use-case?

You can find more info on how to install some other modules in our docs (though you may need to adapt some of the commands for the container): 
https://docs.bitnami.com/installer/components/php/#how-to-install-the-memcache-module

**Comment by FrodeMMeling** [comment]
ok. thanks. 
I fixed it my self.. I use a buildessentials image from you to compile my extensions, then I add them to the image manually. Works fine and keeps this php image small.. The extensions I need for our large business running on CakePhp v2 app are:

memcached
runkit
imagick
redis
yaml
zmq
igbinary
msgpack
xdebug
excel (php_excel using libXL - commercial)

**Comment by gavinzhou** [comment]
@FrodeMMeling 
hi
I wiill add igbinary to bitnami-docker-php-fpm:5.6 docker image

```
docker run --rm bitnami/php-fpm:5.6 bash
```

```
apt-get update
apt-get install build-essential libtool autoconf unzip wget
pecl install igbinary-1.2.1
echo "extension=igbinary.so" >> /opt/bitnami/php/etc/php.ini
```

```
php -m|grep -i igbinary
php -i|grep -i igbinary
```
