### ISSUE TITLE
"/opt/bitnami/nginx/conf/vhosts/dockerapp.conf" failed (21: Is a directory)

### ISSUE THREAD

**Issue by wxb** [bitnami/bitnami-docker-php-fpm#40]
hi, run 
docker run -d -v $HOME/nginx/conf/vhosts:/bitnami/nginx/conf/vhosts/dockerapp.conf --link phpfpm:dockerapp bitnami/nginx

or
docker run -d -v $HOME/nginx/conf/vhosts/dockerapp.conf:/bitnami/nginx/conf/vhosts/dockerapp.conf --link phpfpm:dockerapp bitnami/nginx
container fail
"/opt/bitnami/nginx/conf/vhosts/dockerapp.conf" failed (21: Is a directory)

**Comment by sameersbn** [comment]
@wxb the nginx config expects virtual host configs in the `/bitnami/nginx/conf/vhosts/`. You commands seem to create directories with the suffix `.conf` in the `/bitnami/nginx/conf/vhosts/` directory that seem to confuse nginx.

Assuming that `$HOME/nginx/conf/vhosts/dockerapp.conf` is your vhost config, please try `-v $HOME/nginx/conf/vhosts:/bitnami/nginx/conf/vhosts/`

**Comment by wxb** [comment]
@sameersbn Thank you
