### ISSUE TITLE
Ubuntu 16.04

### ISSUE THREAD

**Issue by chrisvdb** [bitnami/bitnami-docker-php-fpm#41]
Hi,

Would it be possible to upgrade the base package to Ubuntu 16.04?

Thanks,
Chris.

**Comment by chipironcin** [comment]
Hi @chrisvdb 
We are working on it, please see this PR:
https://github.com/bitnami/stacksmith-base/pull/19/files

Will left this issue open until we upgrade the image :)

**Comment by sameersbn** [comment]
@chrisvdb We would like to bring to your attention that we are dropping support for Ubuntu in out Container offering in favor of [bitnami/minideb](https://hub.docker.com/r/bitnami/minideb/) which is a glibc based, light weight and stripped down version of debian and includes `apt` for installing packages from the debian repositories. Thanks to `bitnami/minideb`, the Bitnami Container Images are now far more lightweight. 

For more information on minideb please read out our engineering blog post titled [Minideb: A New Container Base Image](https://engineering.bitnami.com/2016/11/02/minideb-a-new-container-base-image.html). 

Let us know your comments and feedback. We would like to hear back from you.

**Comment by chrisvdb** [comment]
Thanks for letting me know! I will give it a try.

I'll close this request as no longer relevant.
