### ISSUE TITLE
Error executing 'postInstallation': EEXIST: file already exists, symlink '/opt/bitnami/php/conf' -> '/opt/bitnami/php/etc'

### ISSUE THREAD

**Issue by typ431127** [bitnami/bitnami-docker-php-fpm#97]
[root@node71 7.1]# docker run -it -v /data/web:/app -p 9004:9000 typ/php-fpm:1.1

Welcome to the Bitnami php-fpm container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-php-fpm
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-php-fpm/issues
Send us your feedback at containers@bitnami.com

nami    INFO  Initializing php
Error executing 'postInstallation': EEXIST: file already exists, symlink '/opt/bitnami/php/conf' -> '/opt/bitnami/php/etc'

**Comment by sameersbn** [comment]
We have seen such issues when using Docker on RHEL/CentOS and the OverlayFS storage driver. If you are using a similar setup then please take a look at https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/7.2_Release_Notes/technology-preview-file_systems.html for possible workarounds for using OverlayFS with Docker on RHEL 7.2. 

Please let us know if this resolves the issue.

**Comment by typ431127** [comment]
Okay thank you
